### ISSUE TITLE
Prism inconsistent laszer split

### ISSUE THREAD

**Issue by Rucoon** [TeamWizardry/TMT-Refraction#7] opened 2016-11-22 20:01 UTC
The prism changes the way it splits the red green and blue lasers based on direction.  http://i.imgur.com/X1NV6C9.png

**Comment by LordSaad44** [comment] 2016-11-22 20:25
That's how physics works.

**Comment by Rucoon** [comment] 2016-11-23 14:06
Um, what, yes that is not how physics works so that is why it needs to be fixed? All the prisms are facing the same way with the laser hitting the flat back of the prism. But the laser splits differently depending on which compass direction the laser is going. So eatch laser is in the same scenario but acts differently.

**Comment by LordSaad44** [comment] 2016-11-23 14:08
Oh I get what

**Comment by LordSaad44** [comment] 2016-11-23 14:08
*oh I get what you mean.
Definitely a bug

**Comment by TheDeviantCrafter** [comment] 2016-11-26 04:24
I can confirm this bug. I captured this in a test world: https://i.gyazo.com/28bf034b28978a34ac385bee516eb64d.jpg

**Comment by LordSaad44** [comment] 2016-11-27 11:05
@TheDeviantCrafter Yes, the issue is from escapee's math somewhere. We'll see what we can do but math is hard.

**Comment by LordSaad44** [comment] 2017-01-07 14:02
Unfortunately, math is too hard, so we wont be dealing with this any time soon. Sorry :/

Issue will stay open.

**Comment by Eladkay** [comment] 2017-01-07 16:07
But Saad I thought you liked calculus

**Comment by Rikshy** [comment] 2018-07-17 15:46
Closing this issue for clean up.
things have changed with the port to 1.12.2 and i wont support lower versions.
If the problem still occures do not hasitate to create a new issue!

**Closed by Rikshy** 2018-07-17 15:46 UTC
